### ISSUE TITLE
Improve build experience

### ISSUE THREAD

**Issue by robinbb** [LeapYear/sparkle#2]
With the understanding that Docker may be necessary for this, improve the build experience for Sparkle and Mac and Linux.

**Comment by facundominguez** [comment]
@robinbb, can you provide details on what is left to do for the Mac case?
Also, are there any outstanding issues when building on linux?

**Comment by robinbb** [comment]
@facundominguez The Mac build process does not work with "stack --docker", but I have decided to abandon that method.

To document my decision, some details:

Issuing "stack --docker build" terminates with error:

```
    /tmp/stack9/jni-0.1/src/Foreign/JNI.c:2:17:
         fatal error: jni.h: No such file or directory
    compilation terminated.
```

This is because the 'jni' package requires Java (JDK) packages to be installed on the build image. However, they are not.

The 'stack --docker' build process uses a fixed Docker image that is determined by 'stack', and that image has no "jni.h" file. It is possible to supply a build image (stored in Docker Hub, say), but then we would have to include as a phase of our build process a build of that image.

It is possible to do that, but then our build process would include some sort of "docker build ..." command, and then possibly a Docker image upload.

Instead of all of that, I opt for simply building a Docker image which builds Sparkle as part of its build process. That way, we *do* have a "docker build ..." command as part of our build process, but we do not have a "stack --docker" nor a Docker image upload/download.

That is all to say I think that we should not expect to successfully build with "stack --docker" on Mac. We should simply use Docker to build - the Docker image should include 'stack' and 'jni.h' and all other needed dependencies for building. The current Dockerfile has these things.

So, the outstanding issues:
(1) Does "stack --docker" actually succeed on Linux? It should not, I think.
(2) Can we add the source files to the Docker image and just build there?

I am actually working on (2). It would be nice if you were to check (1) and then verify that the build of sparkle works for you on Linux.

**Comment by facundominguez** [comment]
> (1) Does "stack --docker" actually succeed on Linux? It should not, I think

This does work on linux:
```
$ docker build -t sparkle .
$ stack --docker --docker-image sparkle build
```

Is necessary that `stack --docker` works without specifying a docker image? If so we could make the `stack.yaml` file point to the image `sparkle`, and still tell the user to build it before using `stack`.

> (2) Can we add the source files to the Docker image and just build there?

It is possible, but I believe that stack solves this already by sharing folders in the host and the container. IIUC you mentioned that this wasn't working on Mac. Can you share the failure you had?

**Comment by robinbb** [comment]
Another outstanding issue is:

(3) Pin the nixpkgs version used to build.

Currently, we issue

```
RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable && nix-channel --update"
```

in the Dockerfile. This makes for a build that is not reproducible, since it depends on when the Docker image is built. Instead, the exact commit on the nixos/nixpkgs repo should be specified. This can be achieved by making that repo a Git submodule of this repo, and changing the "NIX_PATH" environment variable in the image. Can also be achieved other ways.

@mboes was onboard with this idea, so it should probably be done in such a way that we can submit a PR to the public sparkle repo, too.

**Comment by robinbb** [comment]
@facundominguez (1) No, it is not necessary that "stack --docker" work without specifying a docker image. The fact that it does invalidates my argument, above, about building Docker images, etc.

(2) It works if I accept the default sharing configuration. (I normally do not, because I worry that build scripts might possibly add my private files to the build artifact. Not all share this paranoia.)

So, (1) and (2) are sorted. Only (3) remains!

**Comment by facundominguez** [comment]
Sounds great.

Regarding pinning, I would prefer to avoid using submodules. Perhaps we could use
```
NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-16.09.zip"
```

I've read over there that pinning could stop using the channel cache of binaries. But I don't know enough about nix to understand if it is unavoidable.

**Comment by robinbb** [comment]
I notice that 'stack' supports '--nix-path="nixpkgs=/my/own/nixpkgs/clone"'. See [the docs](https://docs.haskellstack.org/en/stable/nix_integration/).

It is true that pinning might result in the binary cache being used. That is okay, though, because the behaviour in that case is to actually build the missing packages, which should work. If not, we can update the nixpkgs commit to which we refer. Should be very much okay.

**Comment by mboes** [comment]
@robinbb a colleague of @facundominguez, @ypares (Yves), implemented Stack's Nix support. So if you need support or extra features we've got that covered.

I'm very surprised that `stack --docker build` on OS X yields an error from inside the image that doesn't appear on Linux. As confirmed by @facundominguez and I believe by you as well, the build does proceed inside the container at least when starting from a Linux host.

In any case, rather than doubling down on Docker support on OS X, which may not be what you're after, @robinbb might you update the ticket description with specific acceptance criteria for this ticket? Better yet, could you provide a specific sequence of commands that you'd like type in and expect them to work (be it a `stack --docker` based workflow or something different)? At the moment "improve the build experience for Sparkle and Mac and Linux" is a tad open ended. ;)

**Comment by robinbb** [comment]
@mboes The "stack --docker build" error was due to lack of "--docker-image sparkle" I think. For the last while, I have been issuing "stack --docker --docker-image sparkle build" without difficulty on Mac.

Previously, I had problems because I had configured Docker so as not to share directories with containers (for security reasons). I have caved on that matter, for now.  =P

The only thing that remains for acceptance of this issue is to "pin" the nixpkgs version. See my comments in #5

**Comment by robinbb** [comment]
I lied. Here's another issue that we should address: when the 'gradle build' fails, the build as a whole still succeeds. This is probably due to the custom code in Setup.hs. This bit me.

**Comment by mboes** [comment]
Taking the liberty to close this meta issue in favour of companion tickets with a testable definition of "done". nix pinning tracked in #5 and Gradle issue tracked in https://github.com/tweag/sparkle/issues/64.

**Comment by robinbb** [comment]
Thank you for the issue grooming, @mboes, but I will reopen this issue. The reason is this: I have an (almost) 1-1 mapping between issues and contract deliverables. I would like to close the issue if and only if the contract item is complete and accepted. This may mean that I have a few issues like this one which serve only to coordinate other issues (like #5 and #10, for example) by inclusion.

**Comment by robinbb** [comment]
- [x] `stack --docker --docker-image sparkle` works on Mac and Linux
- [x] #5
- [ ] https://github.com/tweag/sparkle/issues/64

**Comment by mboes** [comment]
Ok good to know these kinds of issues are tied to line items in contract deliverables.

**Comment by robinbb** [comment]
We can consider this delivered. Closing.
