### ISSUE TITLE
Configure CI for LeapYear/sparkle

### ISSUE THREAD

**Issue by robinbb** [LeapYear/sparkle#21]

**Comment by robinbb** [comment]
Please include in the CI functionality a check which ensures that the submodule 'inline-java' points to a commit which is on the 'master' branch of that repository. That can be achieved by checking the return value of:

```shell
cd inline-java && git fetch && git branch --contains | grep master
```

**Comment by shijinabraham-leapyear** [comment]
CI job for building master and Pull requests are setup. https://github.com/LeapYear/sparkle/pull/30 needs to be merged in for CI to work.
