### ISSUE TITLE
Test the supported type casting of sparkle data frame expressions

### ISSUE THREAD

**Issue by robinbb** [LeapYear/sparkle#38]
The correctness of code recently added to leapyear-server depends for its correctness on sane automatic casting of types by sparkle. Add test code which shows the conversions that occur. 

For example, consider a spark expression "sqrt x" where x refers to a column of type bool. What happens when we give it a bool, and force it to be used in a context where a double is needed.

We are especially interested in Spark's implicit casting for these conversions:

Int -> Double  (we're pretty sure this works just fine)
Bool -> Double
Bool -> Int

Will spark throw an exception, or will it implicitly convert False -> 0, True -> 1? If it throws an exception then how do we do that cast, what spark DF.Column function do we need to call to do this?

More context: the server's expression type checking now inserts explicit casts (which were previously implicit). So these conversions were being done before, we just didn't notice (and probably have not tested it).

**Comment by alpmestan** [comment]
I augmented the "app" that showcases dataframe functions with the following block:

``` haskell
    do intCol         <- lit (1 :: Int32)
       boolCol        <- lit True
       sqrtIntCol     <- sqrtCol intCol       -- goal: test Int -> Double conversion
       sqrtBoolCol    <- sqrtCol boolCol  -- goal: test Bool -> Double conversion
       intPlusBoolCol <- plus intCol boolCol -- goal: test Bool -> Int conversion
       select df1 [intCol, boolCol, sqrtIntCol {-, sqrtBoolCol -}, intPlusBoolCol]
         >>= debugDF
```

Assuming that my example indeed exercises the conversions we're interested in (I think it does), it turns out that only the Int -> Double implicit conversion gets done, we get an exception for the other two. This seems reasonable, but means we have to do that conversion ourselves explicitly.

For reference, the exceptions:

``` java
Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve '(1 + true)' due to data type mismatch: differing types in '(1 + true)' (int and boolean).;
```

and

``` java
Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'SQRT(true)' due to data type mismatch: argument 1 requires double type, however, 'true' is of boolean type.;
```

**Comment by alpmestan** [comment]
The two type casts that are not implicitly supported but that are of interest to us, namely `Bool -> Int` and `Bool -> Double`, can be done through explicit casts, by using the `cast` method on `Column`s. I've just pushed a PR at #39 that adds a binding to this method to sparkle and some example code that illustrates implicit and explicit (through `cast`) casts to the dataframe demo app.

For reference, the example code looks like this:

``` haskell
    -- implicit and explicit casts
    do intCol         <- lit (1 :: Int32) >>= named "int"
       boolCol        <- lit True >>= named "bool"
       sqrtIntCol     <- sqrtCol intCol >>= named "sqrt(int)"

       -- the following two don't work, no implicit casts
       -- for Bool -> Double and Bool -> Int
       --
       -- sqrtBoolCol    <- sqrtCol boolCol
       -- intPlusBoolCol <- plus intCol boolCol

       castBoolIntCol <- cast boolCol "int"
                     >>= named "cast bool to int"

       castBoolDoubleCol <- cast boolCol "double"
                        >>= named "cast bool to double"

       sqrtBoolIntCol <- sqrtCol castBoolIntCol
                     >>= named "sqrt(cast bool to int)"
       sqrtBoolDoubleCol <- sqrtCol castBoolDoubleCol
                        >>= named "sqrt(cast bool to double)"

       select df1 [ intCol
                  , boolCol
                  , sqrtIntCol
                  , castBoolIntCol
                  , castBoolDoubleCol
                  , sqrtBoolIntCol
                  , sqrtBoolDoubleCol
                  ]
         >>= debugDF
```

And the output:

``` java
+---+----+---------+----------------+-------------------+----------------------+-------------------------+
|int|bool|sqrt(int)|cast bool to int|cast bool to double|sqrt(cast bool to int)|sqrt(cast bool to double)|
+---+----+---------+----------------+-------------------+----------------------+-------------------------+
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
|  1|true|      1.0|               1|                1.0|                   1.0|                      1.0|
+---+----+---------+----------------+-------------------+----------------------+-------------------------+
```

Added you and @dcoutts-2fa as reviewers.

**Comment by robinbb** [comment]
The PR for the `cast` method is now merged.

**Comment by robinbb** [comment]
@alpmestan @dcoutts-2fa Can you two work together to discuss exactly where this desired casting is needed?

**Comment by robinbb** [comment]
We have made another issue for making use of the newly developed casting functions, so I am closing this issue.
