### ISSUE TITLE
Avoid the need for --packages flag to spark-submit

### ISSUE THREAD

**Issue by alpmestan** [LeapYear/sparkle#46]
As part of my work on CSV support (https://github.com/LeapYear/sparkle/pull/45), we encountered for the first time the need for an additional dependency (one not part of Spark -- at least not in Spark 1.6.x). It turns out that we can ask spark-submit/spark-shell/etc to provide us with such an additional dependency (spark-csv in my case) through the `--packages` flag.

However, this is really far from a satisfactory solution in the long term, as it makes spark-submit download the dependency at runtime (and requires us to pass that `--packages <...>` argument _every time we launch a spark application that needs the said package(s)).

In the aforementionned PR, I mention two options that @mboes and I found that would alleviate the need for `--packages`. They would allow us to embed any Java dependency in an application's JAR (creating a so-called "fat JAR") except the ones provided by vanilla spark (spark-core, spark-mllib, etc) which don't have to be provided, as the Spark instance running an application will have those in its classpath.

We eventually want to pick one such option and implement it in sparkle.

**Comment by robinbb** [comment]
Blocked on #44

**Comment by robinbb** [comment]
Well re-open an equivalent issue after migration to Spark 2.0.
