### ISSUE TITLE
Take repo private

### ISSUE THREAD

**Issue by robinbb** [LeapYear/sparkle#73]
For CI reasons, and others, I would like to make this repo private. Please create a 'leapyear-sparkle' repo and follow instructions at https://help.github.com/articles/duplicating-a-repository/ and then configure CI on travis-ci.com for this new repo.

**Comment by shijinabraham-leapyear** [comment]
@robinbb Do we want to keep this repo and keeping getting updates from it or will it be just the leapyear-sparkle repo?
( Ref: Mirroring a repository in another location in https://help.github.com/articles/duplicating-a-repository/ )

**Comment by robinbb** [comment]
@shijinabraham-leapyear No, we will trash this repo, afterward.

**Comment by shijinabraham-leapyear** [comment]
https://github.com/LeapYear/leapyear-sparkle created

**Comment by shijinabraham-leapyear** [comment]
travis build is enabled for pull requests.

**Comment by robinbb** [comment]
@shijinabraham-leapyear Please also give me admin privileges on the repo.

**Comment by shijinabraham-leapyear** [comment]
I can find a option make you admin. I have asked @chalkandpaste

**Comment by shijinabraham-leapyear** [comment]
You should be a admin now.
